import { supabase } from "../lib/supabase";

const dateLabel=(value:string)=>new Date(`${value}T00:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});

export const HrmsService={
 async getStaff(){const{data,error}=await supabase.from("hr_employees").select("*").order("full_name");if(error)throw error;return(data??[]).map(e=>({id:e.id,empCode:e.employee_code,fullName:e.full_name,role:e.job_title,department:e.department,branch:e.branch,email:e.email,phone:e.phone??"",joinDate:dateLabel(e.join_date),baseSalary:Number(e.base_salary),status:e.employment_status,bankAccount:e.bank_account??"",panNumber:e.pan_number??""}))},
 async getAttendance(){const{data,error}=await supabase.from("hr_attendance").select("*,hr_employees(employee_code,full_name)").order("attendance_date",{ascending:false});if(error)throw error;return(data??[]).map(a=>({id:a.id,empCode:a.hr_employees?.employee_code??"—",fullName:a.hr_employees?.full_name??"Unknown",date:dateLabel(a.attendance_date),checkIn:a.clock_in?new Date(a.clock_in).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—",checkOut:a.clock_out?new Date(a.clock_out).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"In Office",status:a.status,lateMinutes:a.late_minutes}))},
 async getLeaves(){const{data,error}=await supabase.from("hr_leave_requests").select("*,hr_employees(employee_code,full_name),staff_profiles!hr_leave_requests_approved_by_fkey(full_name)").order("created_at",{ascending:false});if(error)throw error;return(data??[]).map(l=>({id:l.id,empCode:l.hr_employees?.employee_code??"—",fullName:l.hr_employees?.full_name??"Unknown",leaveType:l.leave_type,fromDate:l.from_date,toDate:l.to_date,days:Number(l.days),reason:l.reason,status:l.status,approvedBy:l.staff_profiles?.full_name}))},
 async getPayroll(){const{data,error}=await supabase.from("hr_payroll_items").select("*,hr_payroll_runs(period_start,period_end,status,paid_at),hr_employees(employee_code,full_name,job_title)");if(error)throw error;return(data??[]).map(p=>({id:p.id,empCode:p.hr_employees?.employee_code??"—",fullName:p.hr_employees?.full_name??"Unknown",role:p.hr_employees?.job_title??"",month:`${p.hr_payroll_runs?.period_start} – ${p.hr_payroll_runs?.period_end}`,basicSalary:Number(p.basic_salary),allowance:Number(p.allowance),commission:Number(p.commission),grossSalary:Number(p.gross_salary),ssfDeduction:Number(p.ssf_deduction),citDeduction:Number(p.cit_deduction),tdsTax:Number(p.tds_tax),netSalary:Number(p.net_salary),status:p.hr_payroll_runs?.status==="PAID"?"PAID":"PROCESSING",paymentDate:p.hr_payroll_runs?.paid_at?dateLabel(p.hr_payroll_runs.paid_at.slice(0,10)):"Pending"}))},
 async createEmployee(payload:Record<string,unknown>){const{error}=await supabase.rpc("hr_create_employee",{payload});if(error)throw error},
 async clockIn(){const{error}=await supabase.rpc("hr_clock_in");if(error)throw error},
 async requestLeave(payload:Record<string,unknown>){const{error}=await supabase.rpc("hr_request_leave",{payload});if(error)throw error},
 async decideLeave(id:string,decision:"APPROVED"|"REJECTED"){const{error}=await supabase.rpc("hr_decide_leave",{leave_uuid:id,decision,decision_note:null});if(error)throw error},
};
