import { AlertTriangle, CheckCircle2, ClipboardList, Plus, X } from "lucide-react";
import { useEffect, useState } from "react";
import { CaseTaskService, type CaseTask } from "../../services/applicationService";

export function CaseTaskPanel(){
 const[tasks,setTasks]=useState<CaseTask[]>([]),[showForm,setShowForm]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[form,setForm]=useState({studentCode:"",title:"",description:"",dueAt:"",priority:"HIGH" as CaseTask["priority"]});
 async function load(){setLoading(true);try{setTasks(await CaseTaskService.list());setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load case tasks")}finally{setLoading(false)}}
 useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
  void load()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();try{await CaseTaskService.create(form);setShowForm(false);setForm({studentCode:"",title:"",description:"",dueAt:"",priority:"HIGH"});await load()}catch(err){setError(err instanceof Error?err.message:"Unable to create task")}}
 async function complete(id:string){try{await CaseTaskService.complete(id);await load()}catch(err){setError(err instanceof Error?err.message:"Unable to complete task")}}
 const overdue=tasks.filter(t=>t.status!=="COMPLETED"&&new Date(t.dueAt)<new Date()).length;
 return <section className="phase3-task-panel"><header><div><span><ClipboardList size={17}/>Case tasks & deadlines</span><small>{overdue>0?`${overdue} overdue tasks require escalation`:"Operational deadline queue"}</small></div><button className="btn-secondary" type="button" onClick={()=>setShowForm(true)}><Plus size={15}/>New task</button></header>{error&&<div className="phase2-alert phase2-alert-error"><AlertTriangle size={16}/>{error}</div>}{loading?<div className="phase3-task-empty">Loading case tasks…</div>:tasks.length===0?<div className="phase3-task-empty">No open case tasks.</div>:<div className="phase3-task-list">{tasks.slice(0,8).map(t=><article key={t.id} className={new Date(t.dueAt)<new Date()&&t.status!=="COMPLETED"?"overdue":""}><div><b>{t.title}</b><small>{t.studentCode} · {t.studentName} · {t.assignee}</small></div><span>{t.priority}</span><time>{new Date(t.dueAt).toLocaleString()}</time>{t.status==="COMPLETED"?<em>Completed</em>:<button type="button" onClick={()=>complete(t.id)}><CheckCircle2 size={15}/>Complete</button>}</article>)}</div>}{showForm&&<div className="modal-backdrop-clean" onClick={()=>setShowForm(false)}><div className="modal-dialog-clean phase2-conversion" onClick={e=>e.stopPropagation()}><div className="modal-header-clean"><h3>Create case task</h3><button className="drawer-close-btn" type="button" onClick={()=>setShowForm(false)}><X size={18}/></button></div><form className="modal-form-clean" onSubmit={submit}><div className="form-group"><label>Student code *</label><input required value={form.studentCode} onChange={e=>setForm({...form,studentCode:e.target.value})} placeholder="AECS-2026-00001"/></div><div className="form-group"><label>Task *</label><input required minLength={2} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="form-row-2"><div className="form-group"><label>Deadline *</label><input type="datetime-local" required value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})}/></div><div className="form-group"><label>Priority</label><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as CaseTask["priority"]})}><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div></div><div className="form-group"><label>Description</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="modal-footer-clean"><button className="btn-secondary" type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="btn-primary" type="submit">Create task</button></div></form></div></div>}</section>
}
