import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{
  const url=Deno.env.get("SUPABASE_URL")!,serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,authorization=req.headers.get("Authorization")||"";const admin=createClient(url,serviceKey,{auth:{persistSession:false}});const token=authorization.replace("Bearer ","");const{data:{user},error:userError}=await admin.auth.getUser(token);if(userError||!user)throw new Error("Unauthorized");const{data:actor}=await admin.from("staff_profiles").select("role,is_active").eq("id",user.id).single();if(!actor?.is_active||!["ADMIN","DIRECTOR"].includes(actor.role))throw new Error("Administrator access required");
  const body=await req.json();if(!body.password||body.password.length<8)throw new Error("Password must contain at least 8 characters");
  if(body.action==="set_password"){if(!body.user_id)throw new Error("Staff member is required");const{error}=await admin.auth.admin.updateUserById(body.user_id,{password:body.password});if(error)throw error;await admin.from("audit_logs").insert({user_id:user.id,action:"STAFF_PASSWORD_UPDATED",module:"staff",metadata:{staff_id:body.user_id}});return json({ok:true});}
  if(body.action!=="create")throw new Error("Invalid action");if(!body.full_name?.trim()||!body.email?.trim())throw new Error("Name and email are required");const allowed=["ADMIN","DIRECTOR","FRONT_DESK","COUNSELLOR","DOCUMENTATION","FINANCE","TEST_BOOKING"];if(!allowed.includes(body.role))throw new Error("Invalid role");const{data:created,error:createError}=await admin.auth.admin.createUser({email:body.email.trim().toLowerCase(),password:body.password,email_confirm:true,user_metadata:{full_name:body.full_name.trim(),role:body.role}});if(createError)throw createError;const{error:profileError}=await admin.from("staff_profiles").upsert({id:created.user.id,full_name:body.full_name.trim(),email:body.email.trim().toLowerCase(),role:body.role,is_active:true});if(profileError)throw profileError;await admin.from("audit_logs").insert({user_id:user.id,action:"STAFF_CREATED",module:"staff",metadata:{staff_id:created.user.id,role:body.role}});return json({ok:true});
}catch(error){return json({error:error instanceof Error?error.message:"Unable to manage staff"},400)}});
