import { FormEvent, useEffect, useState } from "react";
import { KeyRound, Plus, ShieldCheck, UserPlus, Users, X } from "lucide-react";
import { supabase } from "../../lib/supabase";
import { useAuth } from "../auth/AuthProvider";
const roles=["ADMIN","DIRECTOR","FRONT_DESK","COUNSELLOR","DOCUMENTATION","FINANCE","TEST_BOOKING"];
type Staff={id:string;full_name:string;email:string;role:string;is_active:boolean};
async function functionError(error:any){try{const body=await error?.context?.json();return body?.error||error.message}catch{return error?.message||"Request failed"}}
export function AdminDashboard(){
  const{profile}=useAuth();const[staff,setStaff]=useState<Staff[]>([]),[logs,setLogs]=useState<any[]>([]),[adding,setAdding]=useState(false),[passwordTarget,setPasswordTarget]=useState<Staff|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const[form,setForm]=useState({full_name:"",email:"",password:"",role:"FRONT_DESK"});const[newPassword,setNewPassword]=useState("");
  async function load(){const[{data:s},{data:l}]=await Promise.all([supabase.from("staff_profiles").select("*").order("full_name"),supabase.from("audit_logs").select("*,staff_profiles(full_name)").order("created_at",{ascending:false}).limit(50)]);setStaff((s||[]) as Staff[]);setLogs(l||[])}
  useEffect(()=>{load()},[]);
  if(!["ADMIN","DIRECTOR"].includes(profile?.role||""))return <article className="panel forbidden"><ShieldCheck/><h2>Administrator access required</h2></article>;
  async function change(id:string,values:Partial<Staff>){await supabase.from("staff_profiles").update(values).eq("id",id);load()}
  async function addStaff(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");const{error}=await supabase.functions.invoke("invite-staff",{body:{action:"create",...form}});if(error)setMessage(await functionError(error));else{setMessage("Staff account created successfully.");setForm({full_name:"",email:"",password:"",role:"FRONT_DESK"});await load();setTimeout(()=>setAdding(false),900)}setBusy(false)}
  async function setPassword(event:FormEvent){event.preventDefault();if(!passwordTarget)return;setBusy(true);setMessage("");const{error}=await supabase.functions.invoke("invite-staff",{body:{action:"set_password",user_id:passwordTarget.id,password:newPassword}});if(error)setMessage(await functionError(error));else{setMessage("Password updated successfully.");setNewPassword("");setTimeout(()=>setPasswordTarget(null),900);await load()}setBusy(false)}
  return <><section className="page-heading"><div><p className="eyebrow">System administration</p><h2>Staff & permissions</h2><p>Manage staff access, passwords and system activity.</p></div><button className="primary-button" onClick={()=>{setAdding(true);setMessage("")}}><Plus size={16}/>Add staff</button></section><section className="admin-grid"><article className="panel"><div className="panel-head"><div><h3>Staff accounts</h3><p>{staff.length} authorized team members</p></div><Users/></div>{staff.map(s=><div className="staff-row staff-row-actions" key={s.id}><div><strong>{s.full_name}</strong><span>{s.email}</span></div><select value={s.role} onChange={e=>change(s.id,{role:e.target.value})}>{roles.map(role=><option key={role} value={role}>{role.replaceAll("_"," ")}</option>)}</select><label><input type="checkbox" checked={s.is_active} onChange={e=>change(s.id,{is_active:e.target.checked})}/> Active</label><button className="password-button" onClick={()=>{setPasswordTarget(s);setMessage("");setNewPassword("")}}><KeyRound size={14}/>Set password</button></div>)}</article><article className="panel"><div className="panel-head"><div><h3>Audit log</h3><p>Recent security-sensitive actions</p></div><ShieldCheck/></div>{logs.length?logs.map(l=><div className="audit-row" key={l.id}><strong>{l.action}</strong><span>{l.module} · {l.staff_profiles?.full_name||"System"}</span><time>{new Date(l.created_at).toLocaleString()}</time></div>):<p className="admin-empty">No recent administrative activity.</p>}</article></section>
    {adding&&<div className="modal-backdrop" onMouseDown={()=>setAdding(false)}><form className="staff-modal" onSubmit={addStaff} onMouseDown={event=>event.stopPropagation()}><header><div><UserPlus size={20}/><div><h2>Add staff member</h2><p>Create a login with a temporary password.</p></div></div><button type="button" onClick={()=>setAdding(false)} aria-label="Close"><X/></button></header><div className="staff-form"><label>Full name<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Temporary password<input required type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete="new-password"/><small>Minimum 8 characters</small></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(role=><option key={role} value={role}>{role.replaceAll("_"," ")}</option>)}</select></label>{message&&<p className={message.includes("successfully")?"staff-success":"form-error"}>{message}</p>}</div><footer><button type="button" className="secondary-button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?"Creating…":"Create account"}</button></footer></form></div>}
    {passwordTarget&&<div className="modal-backdrop" onMouseDown={()=>setPasswordTarget(null)}><form className="staff-modal password-modal" onSubmit={setPassword} onMouseDown={event=>event.stopPropagation()}><header><div><KeyRound size={20}/><div><h2>Set staff password</h2><p>{passwordTarget.full_name} · {passwordTarget.email}</p></div></div><button type="button" onClick={()=>setPasswordTarget(null)} aria-label="Close"><X/></button></header><div className="staff-form"><label>New password<input required type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoFocus autoComplete="new-password"/><small>Minimum 8 characters. Share it securely with the staff member.</small></label>{message&&<p className={message.includes("successfully")?"staff-success":"form-error"}>{message}</p>}</div><footer><button type="button" className="secondary-button" onClick={()=>setPasswordTarget(null)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?"Updating…":"Update password"}</button></footer></form></div>}
  </>;
}
