import{useState}from"react";import{ArrowLeft,ArrowRight,Check,UserPlus}from"lucide-react";import{registerStudent}from"../student.service";
const steps=["Personal","Academic","Preferences","English Test","Passport","Additional"];
const initial={full_name:"",gender:"",dob:"",whatsapp:"",email:"",current_address:"",highest_qualification:"",current_status:"",latest_result:"",study_gap:"",employment_status:"",preferred_country:"",second_country:"",preferred_intake:"",preferred_course:"",budget:"",test_taken:"false",test_type:"",score:"",has_passport:"false",lead_source:"",message:""};
const field=(name:string,label:string,type="text",required=true,options?:string[])=>({name,label,type,required,options});
const groups=[
 [field("full_name","Full name"),field("gender","Gender","select",true,["Male","Female","Other","Prefer not to say"]),field("dob","Date of birth","date"),field("whatsapp","WhatsApp number"),field("email","Email","email"),field("current_address","Current address","text",false)],
 [field("highest_qualification","Highest qualification"),field("current_status","Current status"),field("latest_result","Latest GPA / percentage", "text",false),field("study_gap","Study gap","text",false),field("employment_status","Employment status","text",false)],
 [field("preferred_country","Preferred country","select",true,["UK","Australia","Canada","USA","Japan","Korea"]),field("second_country","Second choice","select",false,["UK","Australia","Canada","USA","Japan","Korea"]),field("preferred_intake","Preferred intake"),field("preferred_course","Preferred course"),field("budget","Estimated budget (NPR)","number",false)],
 [field("test_taken","Have you taken an English test?","select",true,["true","false"]),field("test_type","Test type","select",false,["IELTS","PTE","Duolingo","TOEFL","GRE","SAT"]),field("score","Score","text",false)],
 [field("has_passport","Do you have a valid passport?","select",true,["true","false"])],
 [field("lead_source","Lead source","select",true,["Walk-in","Referral","Facebook","Instagram","Website","Education fair","Other"]),field("message","Optional message","textarea",false)]
];
export function RegistrationForm(){const[step,setStep]=useState(0);const[form,setForm]=useState(initial);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[success,setSuccess]=useState<{student_code:string}|null>(null);const visible=groups[step].filter(f=>!(step===3&&form.test_taken==="false"&&["test_type","score"].includes(f.name)));const valid=visible.every(f=>!f.required||form[f.name as keyof typeof form]);async function submit(){setBusy(true);setError("");try{const result=await registerStudent({...form,test_taken:form.test_taken==="true",has_passport:form.has_passport==="true"});setSuccess(result)}catch(e){setError(e instanceof Error?e.message:"Registration failed")}finally{setBusy(false)}}if(success)return <article className="success-card"><div><Check size={28}/></div><p className="eyebrow">Registration complete</p><h2>Student registered successfully</h2><p>Student ID</p><strong>{success.student_code}</strong><span className="status-badge new">New Lead</span></article>;
return <><section className="page-heading"><div><p className="eyebrow">Front desk registration</p><h2>Register a new student</h2><p>Complete the six steps to create a verified AECS student record.</p></div></section><div className="stepper">{steps.map((s,i)=><div className={i===step?"step active":i<step?"step done":"step"} key={s}><span>{i<step?<Check size={14}/>:i+1}</span><small>{s}</small></div>)}</div><article className="panel registration-panel"><div className="form-section-head"><span>Step {step+1} of 6</span><h3>{steps[step]} information</h3></div><div className="form-grid">{visible.map(f=><label key={f.name} className={f.type==="textarea"?"wide":""}>{f.label}{f.required&&<b>*</b>}{f.options?<select value={form[f.name as keyof typeof form]} onChange={e=>setForm({...form,[f.name]:e.target.value})}><option value="">Select</option>{f.options.map(o=><option value={o} key={o}>{o==="true"?"Yes":o==="false"?"No":o}</option>)}</select>:f.type==="textarea"?<textarea value={form[f.name as keyof typeof form]} onChange={e=>setForm({...form,[f.name]:e.target.value})}/>:<input type={f.type} value={form[f.name as keyof typeof form]} onChange={e=>setForm({...form,[f.name]:e.target.value})}/>}</label>)}</div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button className="secondary-button" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>Back</button>{step<5?<button className="primary-button" disabled={!valid} onClick={()=>setStep(step+1)}>Continue<ArrowRight size={16}/></button>:<button className="primary-button" disabled={!valid||busy} onClick={submit}><UserPlus size={16}/>{busy?"Registering…":"Register student"}</button>}</div></article></>}
